language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y tesseract-ocr ghostscript imagemagick poppler-utils
install: 
    - "pip install -r requirements.txt"
    - "pip install pytest mock pytest-catchlog"
    - "pip install ."
script: 
    - "pytest test"
