language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          env: PYVER=2.7
        - os: linux
          sudo: required
          python: 3.5
          env: PYVER=3.5
        - os: linux
          sudo: required
          python: 3.6
          env: PYVER=3.6
        - os: osx
          language: generic
          env: PYVER=2.7
        - os: osx
          language: generic
          env: PYVER=3.5
        - os: osx
          language: generic
          env: PYVER=3.6


before_install:
    - ./.travis_install.sh
install: 
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi;
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then source activate test_env; fi;
    - pip install -r requirements.txt
    - pip install pytest mock
    - pip install .
script: 
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi;
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then source activate test_env; fi;
    - pytest test
